<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run()
    {
        // Mengambil ID staf dengan level Admin
        $adminStaffID = DB::table('Staff')->where('Level', 'ADMIN')->inRandomOrder()->value('StaffID');
        
        // Data produk yang akan di-insert
        $products = [
            [
                'ProductID' => 'RMF001',
                'ProductName' => 'Paket Nasi Ayam Bakar, Perkedel, Terong Teri',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 25000,
                'Description' => 'Paket nasi ayam bakar dengan perkedel dan terong teri.',
                'ImageProduct' => 'public/images/menu/package/paketnasiayambakarperkedelterongteri.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF002',
                'ProductName' => 'Paket Nasi Ayam Remas',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 24000,
                'Description' => 'Paket nasi dengan ayam remas.',
                'ImageProduct' => 'public/images/menu/package/paketnasiayamremas.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF003',
                'ProductName' => 'Paket Nasi Ayam Pop-Terong Teri',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 26000,
                'Description' => 'Paket nasi dengan ayam pop dan terong teri.',
                'ImageProduct' => 'public/images/menu/package/paketnasiayampopterongteri.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF004',
                'ProductName' => 'Paket Nasi Rendang-Ayam Goreng',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 47000,
                'Description' => 'Paket nasi dengan rendang dan ayam goreng.',
                'ImageProduct' => 'public/images/menu/package/paketnasirendangayamgoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF005',
                'ProductName' => 'Paket Nasi Rendang-Telor Dadar',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 32000,
                'Description' => 'Paket nasi dengan rendang dan telor dadar.',
                'ImageProduct' => 'public/images/menu/package/paketnasirendangtelordadar.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF006',
                'ProductName' => 'Paket Nasi Tunjang',
                'Category' => 'PACKAGE',
                'QtyProduct' => 100,
                'UnitPrice' => 36000,
                'Description' => 'Paket nasi dengan tunjang yang empuk.',
                'ImageProduct' => 'public/images/menu/package/paketnasitunjang.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF007',
                'ProductName' => 'Asam Padeh Daging',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 18000,
                'Description' => 'Nikmati kelezatan daging asam padeh kami yang khas dan menggugah selera. Dibuat dengan bumbu rempah yang melimpah, setiap gigitan menghadirkan sensasi cita rasa yang memikat.',
                'ImageProduct' => 'public/images/menu/sidedish/asampadehdaging.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF008',
                'ProductName' => 'Ayam Bakar',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 17000,
                'Description' => 'Dibuat dengan daging ayam segar pilihan dan dipadukan dengan bumbu-bumbu khas serta rempah-rempah berkualitas untuk menghadirkan cita rasa otentik dan memikat.',
                'ImageProduct' => 'public/images/menu/sidedish/ayambakar.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF009',
                'ProductName' => 'Ayam Goreng',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 18000,
                'Description' => 'Kelezatan ayam goreng kami tidak tertandingi! Dibumbui dengan rempah-rempah pilihan, kulitnya renyah dan dagingnya juicy. Nikmati kepuasan setiap gigitannya!',
                'ImageProduct' => 'public/images/menu/sidedish/ayamgoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF010',
                'ProductName' => 'Ayam Gulai',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 18000,
                'Description' => 'Ayam gulai dengan kuah santan yang gurih, memberikan cita rasa istimewa untuk berbagai macam hidangan.',
                'ImageProduct' => 'public/images/menu/sidedish/ayamgulai.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF011',
                'ProductName' => 'Ayam Kalio Lado Ijo',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 19000,
                'Description' => 'Ayam kalio lado ijo kami diolah dengan bumbu rempah yang autentik. Dibumbui dengan bahan-bahan berkualitas, nikmati sensasi cita rasa yang memikat dalam setiap gigitannya!',
                'ImageProduct' => 'public/images/menu/sidedish/ayamkalioladoijo.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF012',
                'ProductName' => 'Ayam Pop',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 19000,
                'Description' => 'Ayam pop kami sajikan dengan kulit renyah dan daging juicy yang menggugah selera. Dibumbui dengan rempah-rempah pilihan, setiap suapannya menghadirkan kepuasan yang tiada duanya.',
                'ImageProduct' => 'public/images/menu/sidedish/ayampop.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF013',
                'ProductName' => 'Ayam Rendang',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 19000,
                'Description' => 'Rendang ayam kami hadir dengan cita rasa otentik dan memikat. Disajikan dengan kuah kental dan bumbu rempah yang meresap sempurna di dalam daging ayam, nikmati kelezatannya dalam setiap suapan!',
                'ImageProduct' => 'public/images/menu/sidedish/ayamrendang.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF014',
                'ProductName' => 'Dendeng Batako',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 19000,
                'Description' => 'Nikmati sensasi pedas manis dendeng balado yang gurih dan lezat. Dibuat dengan bahan-bahan berkualitas dan balutan rempah balado yang khas.',
                'ImageProduct' => 'public/images/menu/sidedish/dendengbatako.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF015',
                'ProductName' => 'Gulai Cincang',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 25000,
                'Description' => 'Nikmati kelezatan gulai cincang kami yang kaya akan rempah-rempah pilihan. Setiap suapannya membawa cita rasa yang memanjakan lidah dan memuaskan selera!',
                'ImageProduct' => 'public/images/menu/sidedish/gulaicincang.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF016',
                'ProductName' => 'Gulai Tunjang',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 20000,
                'Description' => 'Rasakan kelezatan gulai tunjang kami yang lezat dan menggugah selera. Dibuat dengan rempah-rempah pilihan, nikmati sensasi cita rasa yang autentik dalam setiap suapannya!',
                'ImageProduct' => 'public/images/menu/sidedish/gulaitunjang.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF017',
                'ProductName' => 'Ikan Gurame Bakar',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 17000,
                'Description' => 'Nikmati sensasi gurame bakar kami yang lezat dan segar. Disajikan dengan bumbu-bumbu pilihan, setiap gigitan memberikan cita rasa yang memikat dari laut!',
                'ImageProduct' => 'public/images/menu/sidedish/ikanguramebakar.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF018',
                'ProductName' => 'Ikan Gurame Goreng',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 16000,
                'Description' => 'Dihadirkan dengan bahan-bahan terbaik, kami menawarkan cita rasa yang menggugah selera. Nikmati kesegaran ikan gurame yang digoreng sempurna di setiap gigitannya!',
                'ImageProduct' => 'public/images/menu/sidedish/ikanguramegoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF019',
                'ProductName' => 'Ikan Kembung Bakar',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 16000,
                'Description' => 'Kami hadirkan ikan kembung bakar lezat dengan cita rasa asli laut. Rasakan kesegaran dan kelezatan yang tiada duanya dalam setiap potongan!',
                'ImageProduct' => 'public/images/menu/sidedish/ikankembungbakar.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF020',
                'ProductName' => 'Ikan Kembung Goreng',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 15000,
                'Description' => 'Nikmati ikan kembung goreng kami yang renyah di luar, lembut di dalam. Rasakan cita rasa laut yang autentik dalam setiap suapan!',
                'ImageProduct' => 'public/images/menu/sidedish/ikankembunggoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF021',
                'ProductName' => 'Ikan Tuna Blado',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 15000,
                'Description' => 'Kelezatan ikan tuna balado kami akan memanjakan lidah Anda dengan perpaduan pedas dan manis yang sempurna. Rasakan kesegaran dan kaya rasa ikan tuna yang terjaga dalam balado khas kami!',
                'ImageProduct' => 'public/images/menu/sidedish/ikantunabalado.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF022',
                'ProductName' => 'Ikan Tuna Gulai',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 15000,
                'Description' => 'Kami sajikan ikan tuna gulai kuning dengan cita rasa yang khas dan menggugah selera. Setiap potongan tuna yang lembut terendam dalam kuah kuning yang gurih dan nikmat.',
                'ImageProduct' => 'public/images/menu/sidedish/ikantunagulai.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF023',
                'ProductName' => 'Rendang',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 17000,
                'Description' => 'Dibuat penuh cinta dengan daging sapi pilihan dan disempurnakan dengan rempah-rempah berkualitas, menghadirkan cita rasa yang tak tertandingi.',
                'ImageProduct' => 'public/images/menu/sidedish/rendangdaging.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF024',
                'ProductName' => 'Sop Daging',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 25000,
                'Description' => 'Nikmati kehangatan dan kelezatan sop daging kami yang diolah dengan bumbu rempah yang kaya. Setiap sendokannya menghadirkan cita rasa yang memanjakan lidah dan menenangkan jiwa.',
                'ImageProduct' => 'public/images/menu/sidedish/sopdaging.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF025',
                'ProductName' => 'Udang Balado',
                'Category' => 'SIDEDISH',
                'QtyProduct' => 100,
                'UnitPrice' => 22000,
                'Description' => 'Udang balado kami diolah dengan bumbu balado yang kaya dan menggugah selera. Rasakan kesegaran dan kelezatan udang dalam balado khas kami!',
                'ImageProduct' => 'public/images/menu/sidedish/udangbalado.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF026',
                'ProductName' => 'Air Mineral',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 8000,
                'Description' => 'Nikmati kesegaran air mineral kami yang menghilangkan dahaga. Dibuat dengan kualitas terbaik, setiap tegukan memberikan kepuasan yang sejati.',
                'ImageProduct' => 'public/images/menu/drink/air.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF027',
                'ProductName' => 'Es Jeruk',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 10000,
                'Description' => 'Nikmati kesegaran es jeruk kami yang menyegarkan. Disajikan dingin, setiap tegukan memberikan sensasi rasa yang menyegarkan dan memikat.',
                'ImageProduct' => 'public/images/menu/drink/esjeruk.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF028',
                'ProductName' => 'Es Teh Manis',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 7000,
                'Description' => 'Nikmati kesegaran es teh manis kami yang diolah dengan rasa yang autentik. Disajikan dingin, setiap tegukan memberikan kepuasan yang tiada duanya.',
                'ImageProduct' => 'public/images/menu/drink/estehmanis.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF029',
                'ProductName' => 'Es Teh Tarik',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 15000,
                'Description' => 'Nikmati kesegaran es teh tarik kami yang khas dan menggugah selera! Disajikan dingin, setiap tegukan memberikan kelezatan yang tiada duanya.',
                'ImageProduct' => 'public/images/menu/drink/estehtarik.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF030',
                'ProductName' => 'Jus Alpukat',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 17000,
                'Description' => 'Jus alpukat kami hadir dengan rasa kaya dan menggugah selera. Dibuat dengan alpukat pilihan, nikmati kelezatan yang tiada duanya.',
                'ImageProduct' => 'public/images/menu/drink/jusalpukat.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF031',
                'ProductName' => 'Jus Mangga',
                'Category' => 'DRINK',
                'QtyProduct' => 100,
                'UnitPrice' => 17000,
                'Description' => 'Jus mangga kami sajikan dengan rasa segar dan kaya akan nutrisi. Dibuat dengan buah mangga terbaik, setiap tegukan memberikan kesegaran yang sejati.',
                'ImageProduct' => 'public/images/menu/drink/jusmangga.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF032',
                'ProductName' => 'Tahu Goreng',
                'Category' => 'OTHER',
                'QtyProduct' => 100,
                'UnitPrice' => 5000,
                'Description' => 'Tahu goreng kami hadir dengan cita rasa otentik. Dibuat dengan tahu berkualitas, nikmati kelezatan yang tiada duanya!',
                'ImageProduct' => 'public/images/menu/other/tahugoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF033',
                'ProductName' => 'Tempe Goreng',
                'Category' => 'OTHER',
                'QtyProduct' => 100,
                'UnitPrice' => 5000,
                'Description' => 'Tempe goreng kami hadir dengan rasa renyah di luar, lembut di dalam. Dibuat dengan bumbu rempah pilihan, nikmati kelezatan yang memikat!',
                'ImageProduct' => 'public/images/menu/other/tempegoreng.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
            [
                'ProductID' => 'RMF034',
                'ProductName' => 'Tumis Toge',
                'Category' => 'OTHER',
                'QtyProduct' => 100,
                'UnitPrice' => 8000,
                'Description' => 'Tumis toge kami hadir dengan rasa yang segar dan menggugah selera. Dibuat dengan bahan-bahan berkualitas, nikmati kelezatan yang tiada duanya!',
                'ImageProduct' => 'public/images/menu/other/tumistoge.png',
                'RatingProduct' => 4.5,
                'CreatedBy' => $adminStaffID,
                'CreatedDate' => now(),
            ],
        ];

        // Menyisipkan data produk ke dalam tabel Products
        DB::table('Products')->insert($products);
    }
}